version: '2'
services:
  tinc:
    image: timbobkov/tinc:1.1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - NODENAME=node0
      - INTERFACE=tun0
      - ADDRESS_FAMILY=ipv4
      - ADDRESS=192.168.43.190
      - SUBNET=172.16.0.0/24
      - VPN_IP=172.16.0.1
      - AUTO_CONNECT=yes
      - LOG_LEVEL=3
      - MODE=switch
    volumes:
      - ./config:/etc/tinc
      - ./scripts:/etc/tinc/scripts
    ports:
      - 655/tcp
      - 655/udp
    network_mode: host
    container_name: tinc